import Head from "next/head";
import { useState } from "react";
import Profile from "../components/profile";
import Tracker from "../components/tracker";
import data from "../data.json";

export default function Home() {
  const [timeframe, setTimeframe] = useState("daily");
  return (
    <div className=" h-screen ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" max-w-screen-md mx-auto mt-24 font-sans">
        <div className="grid sm:grid-rows-2 sm:grid-cols-4 gap-6 p-4">
          <Profile timeframe={timeframe} setTimeframe={setTimeframe} />
          <Tracker data={data} timeframe={timeframe} />
        </div>
      </section>
      <div className="text-center text-white py-10 font-light">
        Challenge by{" "}
        <a
          className="text-gray-400"
          href="https://www.frontendmentor.io/challenges/time-tracking-dashboard-UIQ7167Jw"
          target="_blank"
          rel="noreferrer"
        >
          Frontend Mentor
        </a>
        . Coded by{" "}
        <a
          className="text-blue-600"
          href="https://www.frontendmentor.io/profile/chris-melvin"
        >
          Chris Melvin
        </a>
        .
      </div>
    </div>
  );
}
